# Generated by Django 4.2 on 2023-06-02 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vote_choice_remove_vote_poll_and_more'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(upload_to='task/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_passed', models.BooleanField(default=False, verbose_name='Задание пройдено')),
                ('file', models.FileField(upload_to='answer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc'])])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.tasks', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Итог практической работы',
                'verbose_name_plural': 'Итоги практических',
            },
        ),
    ]
