# Generated by Django 4.2 on 2023-06-03 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_tasks_file_taskanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='file',
            field=models.FileField(upload_to='answer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
