# Generated by Django 4.2 on 2023-06-02 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='poll.choice')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='poll.poll')),
                ('testing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.testing', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Итог тестирования',
                'verbose_name_plural': 'Итоги тестирований',
            },
        ),
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_passed', models.BooleanField(default=False, verbose_name='Задание пройдено')),
                ('file', models.FileField(upload_to='answer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc'])])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.tasks', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Итог практической работы',
                'verbose_name_plural': 'Итоги практических',
            },
        ),
    ]
