# Generated by Django 4.2 on 2023-06-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vote_choice_remove_vote_poll_and_more'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='poll.choice')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='poll.poll')),
                ('testing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.testing', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Итог тестирования',
                'verbose_name_plural': 'Итоги тестирований',
            },
        ),
    ]
