# Generated by Django 4.2 on 2023-06-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_testing_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ManyToManyField(related_name='Ответ', to='poll.poll'),
        ),
    ]
