# Generated by Django 4.2 on 2023-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_choice_poll_choice_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='testing_id',
        ),
        migrations.AddField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(related_name='Ответы', to='poll.choice'),
        ),
        migrations.AddField(
            model_name='testing',
            name='polls',
            field=models.ManyToManyField(related_name='Ответы', to='poll.poll'),
        ),
    ]
